"""Fixtures for recording E2E: BlackHole audio injection.

The recording scenario needs real audio on the system mic for Heidi to produce
a transcript. `audio_injection` routes I/O to BlackHole and plays a chosen clip
(looping only if the clip is shorter than the recording), then restores the
original devices.

Clips (generated by scripts/setup_audio.sh via macOS `say`):
  assets/consult_30s.wav    short clip for the fast e2e check
  assets/consult_5min.wav   real ~5min multi-topic consult
  assets/consult_10min.wav  real ~8-10min multi-topic consult

If BlackHole isn't installed the fixture degrades to a no-op so the UI flow
still runs. Tests that REQUIRE audio should also request `require_blackhole`.
"""
import os
from pathlib import Path

import pytest

from lib import audio

ASSETS = Path(__file__).resolve().parent.parent.parent / "assets"
DEFAULT_CLIP = ASSETS / "consult_30s.wav"
RECORD_SECONDS = float(os.environ.get("RECORD_SECONDS", "30"))


@pytest.fixture()
def require_blackhole():
    if not audio.blackhole_available():
        pytest.skip(
            "BlackHole not available — run scripts/setup_audio.sh and reboot. "
            "See docs for macOS audio setup."
        )


@pytest.fixture()
def audio_injection():
    """Yield start(seconds, clip=None) that plays a clip via BlackHole.

    - clip: path to a wav; defaults to the 30s consult.
    - Routing is only switched if BlackHole is present; otherwise no-op so the
      UI flow still runs.
    """
    router = None
    procs = []

    def start(seconds: float = RECORD_SECONDS, clip: str | Path | None = None):
        nonlocal router
        clip_path = Path(clip) if clip else DEFAULT_CLIP
        if not clip_path.exists():
            pytest.skip(f"Clip missing: {clip_path} (run scripts/setup_audio.sh)")
        if audio.blackhole_available():
            router = audio.AudioRouter()
            router.__enter__()
            procs.append(audio.play_clip(clip_path, seconds))
        # else: no audio device — caller still drives the UI

    yield start

    for p in procs:
        audio.stop_clip(p)
    if router is not None:
        router.__exit__(None, None, None)
